const ADD_ITEM = 'ADD_ITEM'
const INCREASE_ITEM = 'INCREASE_ITEM'
const DECREASE_ITEM = 'DECREASE_ITEM'
const REMOVE_ONE = 'REMOVE_ONE'
const TOTAL_ITEMS = 'TOTAL_ITEMS'
const ERROR = 'ERROR'

const GET_HOME_PRODUCT = 'GET_HOME_PRODUCT';
const ERROR = 'ERROR';

const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
const USER_ACTIVE = 'USER_ACTIVE'
const LOGIN_UNSUCCESSFUL = 'LOGIN_UNSUCCESSFUL'
const ERROR = 'ERROR'

const LOGOUT_USER = 'LOGOUT_USER'

const GET_NEW_PRODUCTS = 'GET_NEW_PRODUCTS'
const ERROR = 'ERROR'

const ORDER_CREATED = 'ORDER_CREATED'
const ORDER_UPDATED = 'ORDER_UPDATED'
const ORDER_DELETED = 'ORDER_DELETED'
const ORDER_PROCESSED = 'ORDER_PROCESSED'

const ERROR = "ERROR"
const GET_PRODUCTS = 'GET_PRODUCTS'

const POST_USER_REGISTER = 'POST_USER_REGISTER';
const ERROR = 'ERROR';

const GET_SHOP_PRODUCTS = 'GET_SHOP_PRODUCTS'
const ERROR = 'ERROR'