"""empty message

Revision ID: 1c4428b367bd
Revises: 9471bd44ac56
Create Date: 2021-08-31 18:01:42.945553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4428b367bd'
down_revision = '9471bd44ac56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden', sa.Column('provincia', sa.String(length=150), nullable=True))
    op.add_column('orden', sa.Column('distrito', sa.String(length=150), nullable=False))
    op.add_column('orden', sa.Column('direccion', sa.Text(), nullable=False))
    op.add_column('orden', sa.Column('telefono', sa.String(length=150), nullable=False))
    op.add_column('orden', sa.Column('metodo_pago', sa.String(length=250), nullable=False))
    op.create_foreign_key(None, 'orden', 'usuario', ['provincia'], ['provincia'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orden', type_='foreignkey')
    op.drop_column('orden', 'metodo_pago')
    op.drop_column('orden', 'telefono')
    op.drop_column('orden', 'direccion')
    op.drop_column('orden', 'distrito')
    op.drop_column('orden', 'provincia')
    # ### end Alembic commands ###
