"""empty message

Revision ID: 2c9795cb660e
Revises: b98ba1aa4935
Create Date: 2021-06-08 20:24:41.126048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9795cb660e'
down_revision = 'b98ba1aa4935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orden', 'cantidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
