"""empty message

Revision ID: 30bd058cfd90
Revises: f8329d331413
Create Date: 2021-08-08 18:46:30.796651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bd058cfd90'
down_revision = 'f8329d331413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('img', sa.String(length=225), nullable=False))
    op.add_column('candela', sa.Column('nuevo', sa.Boolean(), nullable=False))
    op.drop_column('candela', 'imagen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('imagen', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_column('candela', 'nuevo')
    op.drop_column('candela', 'img')
    # ### end Alembic commands ###
