"""empty message

Revision ID: 5eded02f3ada
Revises: 30bd058cfd90
Create Date: 2021-08-08 18:47:35.834729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eded02f3ada'
down_revision = '30bd058cfd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('img', sa.String(length=225), nullable=False))
    op.add_column('candela', sa.Column('nuevo', sa.Boolean(), nullable=False))
    op.drop_column('candela', 'imagen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('imagen', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_column('candela', 'nuevo')
    op.drop_column('candela', 'img')
    # ### end Alembic commands ###
