"""empty message

Revision ID: 8aee0ac135b1
Revises: 71d74343cf68
Create Date: 2021-08-31 14:13:56.506446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aee0ac135b1'
down_revision = '71d74343cf68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('portada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candela', 'portada')
    # ### end Alembic commands ###
