"""empty message

Revision ID: 9471bd44ac56
Revises: c3a8cf85c845
Create Date: 2021-08-31 15:28:16.964689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9471bd44ac56'
down_revision = 'c3a8cf85c845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candela', 'portada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('portada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
