"""empty message

Revision ID: b98ba1aa4935
Revises: 
Create Date: 2021-06-07 22:32:56.678962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98ba1aa4935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=150), nullable=False),
    sa.Column('primer_apellido', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('clave', sa.LargeBinary(length=256), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=150), nullable=False),
    sa.Column('esencia', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=150), nullable=False),
    sa.Column('primer_apellido', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('clave', sa.LargeBinary(length=256), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('productos', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden')
    op.drop_table('usuario')
    op.drop_table('candela')
    op.drop_table('administrador')
    # ### end Alembic commands ###
