"""empty message

Revision ID: c3a8cf85c845
Revises: 8aee0ac135b1
Create Date: 2021-08-31 15:13:02.045705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a8cf85c845'
down_revision = '8aee0ac135b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candela', 'portada',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candela', 'portada',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
