"""empty message

Revision ID: d0678d44e8d1
Revises: d5e78358f092
Create Date: 2021-09-03 13:50:26.659151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0678d44e8d1'
down_revision = 'd5e78358f092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('home_img', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_active')
    op.drop_column('candela', 'home_img')
    # ### end Alembic commands ###
