"""empty message

Revision ID: d5e78358f092
Revises: 1c4428b367bd
Create Date: 2021-08-31 18:03:12.813550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e78358f092'
down_revision = '1c4428b367bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden', sa.Column('distrito', sa.String(length=150), nullable=False))
    op.add_column('orden', sa.Column('direccion', sa.Text(), nullable=False))
    op.add_column('orden', sa.Column('telefono', sa.String(length=150), nullable=False))
    op.add_column('orden', sa.Column('metodo_pago', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orden', 'metodo_pago')
    op.drop_column('orden', 'telefono')
    op.drop_column('orden', 'direccion')
    op.drop_column('orden', 'distrito')
    # ### end Alembic commands ###
