"""empty message

Revision ID: db3124f805e0
Revises: f683665f6676
Create Date: 2021-08-06 15:43:52.355533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3124f805e0'
down_revision = 'f683665f6676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('nombre', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candela', 'nombre')
    # ### end Alembic commands ###
