"""empty message

Revision ID: e6812de062d0
Revises: d0678d44e8d1
Create Date: 2021-09-03 14:01:52.390744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6812de062d0'
down_revision = 'd0678d44e8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candela', 'home_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('home_img', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
