"""empty message

Revision ID: f683665f6676
Revises: 35ffa54c39ce
Create Date: 2021-08-04 11:34:49.655747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f683665f6676'
down_revision = '35ffa54c39ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candela', sa.Column('descripcion', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candela', 'descripcion')
    # ### end Alembic commands ###
