"""empty message

Revision ID: f8329d331413
Revises: db3124f805e0
Create Date: 2021-08-06 16:53:22.644107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8329d331413'
down_revision = 'db3124f805e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
